# Generated by Django 3.2.8 on 2021-10-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appward', '0002_auto_20211022_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='information',
            new_name='info',
        ),
    ]
